In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import requests
from bs4 import BeautifulSoup

In [3]:
import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

In [4]:
url = 'https://finance.naver.com/item/sise_day.naver?code=005930&page=11'

In [5]:
res = requests.get(url)
soup = BeautifulSoup(res.text, 'html.parser')

In [6]:
pd.read_html(res.text)

ValueError: No tables found

In [11]:
driver = webdriver.Chrome()
driver.get(url)

In [12]:
html = driver.page_source

df = pd.read_html(html)[0]
df.dropna(inplace = True)
df

# driver.close()

            날짜       종가     전일비       시가       고가       저가         거래량
1   2021.09.09  75300.0  1000.0  76400.0  76600.0  75000.0  17600770.0
2   2021.09.08  76300.0   200.0  76000.0  76400.0  75600.0  11798147.0
3   2021.09.07  76100.0  1200.0  77100.0  77100.0  75900.0  13239401.0
4   2021.09.06  77300.0   700.0  76800.0  77600.0  76600.0  12861180.0
5   2021.09.03  76600.0   600.0  76400.0  76700.0  76000.0  12096419.0
9   2021.09.02  76000.0   800.0  76800.0  76800.0  75700.0  15347486.0
10  2021.09.01  76800.0   100.0  76700.0  77100.0  75900.0  16114775.0
11  2021.08.31  76700.0  2100.0  74900.0  76700.0  74300.0  24630370.0
12  2021.08.30  74600.0   300.0  75400.0  75500.0  74200.0  12686999.0
13  2021.08.27  74300.0   300.0  74300.0  75000.0  73800.0  15172748.0

In [15]:
df = pd.read_csv('universe_code.csv')
codes = df.종목코드.apply(lambda x : x[1:]).values
codes

array(['000210', '000220', '000240', '000250', '000660', '000990',
       '001340', '001390', '001500', '001750', '001800', '001820',
       '001880', '002310', '002350', '002390', '002870', '003090',
       '003220', '003410', '003530', '003550', '003670', '003780',
       '003850', '004000', '004170', '004490', '004590', '005290',
       '005670', '005690', '005880', '005930', '006060', '006220',
       '006390', '006400', '006620', '006650', '006740', '007330',
       '007340', '007570', '007700', '008490', '009150', '009420',
       '009780', '009970', '010050', '010130', '010240', '010640',
       '010780', '011040', '011170', '011330', '011780', '012330',
       '012510', '012630', '012700', '012750', '012790', '013030',
       '013120', '013810', '013890', '014570', '014680', '014830',
       '015230', '015710', '016090', '016360', '016580', '016600',
       '016610', '017040', '017510', '017890', '017960', '018250',
       '018260', '018310', '019550', '020000', '020150', '020710',
       '021080', '021240', '022220', '023590', '023600', '023760',
       '023770', '023900', '023910', '024110', '024120', '024720',
       '025900', '026890', '026960', '027360', '027410', '027970',
       '028100', '028670', '029460', '029780', '029960', '030190',
       '030210', '030520', '030530', '030610', '031390', '031430',
       '032080', '032190', '032500', '032560', '032620', '032850',
       '033100', '033130', '033160', '033270', '033290', '033500',
       '033640', '033660', '033780', '033830', '034810', '034830',
       '035250', '035420', '035460', '035600', '035900', '036120',
       '036200', '036480', '036490', '036530', '036560', '036570',
       '036800', '036810', '036830', '036890', '036930', '038390',
       '038540', '038870', '039010', '039340', '039420', '039440',
       '039490', '039840', '039860', '040160', '040420', '040910',
       '041460', '041830', '041910', '041920', '042370', '042500',
       '042510', '042700', '043150', '044060', '044340', '044450',
       '045060', '045300', '045520', '046110', '046310', '046440',
       '047770', '047810', '049070', '049720', '049960', '050760',
       '050960', '051360', '051600', '051900', '052260', '052330',
       '052400', '052690', '052790', '052860', '053030', '053210',
       '053300', '053610', '053690', '053800', '054040', '054450',
       '054670', '054950', '055490', '055550', '056190', '056360',
       '058400', '058470', '058630', '059090', '059120', '059210',
       '060150', '060250', '060540', '060980', '061970', '062970',
       '063160', '063760', '064290', '064760', '064960', '065130',
       '065370', '065510', '065680', '066670', '067080', '067160',
       '067830', '067900', '068270', '068330', '068790', '068930',
       '069080', '069260', '069960', '071050', '071200', '072020',
       '072990', '073010', '073110', '073490', '075130', '077360',
       '078140', '078340', '079940', '079960', '080000', '081000',
       '081660', '082920', '083450', '083550', '083930', '084110',
       '084370', '084680', '084850', '086390', '086450', '086520',
       '086670', '086790', '086900', '088130', '088980', '089030',
       '089140', '089600', '089790', '089890', '089970', '089980',
       '090460', '090850', '091440', '091700', '091990', '092440',
       '092730', '093320', '093520', '094820', '094840', '094850',
       '095610', '095660', '096240', '096530', '097230', '097520',
       '097800', '097870', '098460', '099190', '099320', '100120',
       '100250', '100700', '100790', '101160', '101240', '101490',
       '102120', '102710', '104460', '104540', '104830', '105560',
       '105740', '108380', '108490', '109740', '110990', '111710',
       '111770', '114090', '115960', '119610', '119860', '120240',
       '121600', '122310', '122450', '122990', '123890', '126560',
       '127710', '128940', '130660', '131030', '131290', '131370',
       '131390', '131970', '136540', '137950', '138080', '138930',
       '139130', '140860', '141000', '141080', '143240', '144960',
       '145020', '145720', '147830', '148150', '149950', '149980',
       '151860', '161390', '166090', '169330', '170790', '170900',
       '171010', '171090', '171120', '175330', '178320', '178920',
       '179290', '179900', '183300', '186230', '187870', '189300',
       '189690', '189980', '192080', '192250', '192440', '194700',
       '198080', '200130', '200470', '200670', '200780', '201490',
       '203450', '203650', '204270', '204620', '205100', '206400',
       '206640', '207760', '207940', '208350', '208710', '210540',
       '210980', '213420', '214150', '214180', '214270', '214320',
       '214450', '215200', '216050', '217190', '217500', '217600',
       '217820', '218410', '219420', '221840', '222080', '225330',
       '225530', '225590', '226340', '227840', '228670', '228850',
       '230360', '234080', '234340', '234690', '236200', '237750',
       '237820', '238200', '238490', '240810', '241560', '241590',
       '241690', '241770', '241790', '243070', '243840', '247540',
       '250000', '251270', '251370', '251630', '251970', '253450',
       '255440', '258830', '260660', '263600', '263690', '263720',
       '263750', '263860', '264450', '264660', '267320', '267790',
       '270520', '270870', '271560', '272110', '272290', '272550',
       '277410', '278280', '278650', '281740', '281820', '282690',
       '284740', '285490', '290120', '290270', '290380', '290520',
       '290650', '290670', '290720', '293480', '297090', '299900',
       '300120', '302430', '306040', '308100', '312610', '317330',
       '322180', '327260', '900250', '900270', '900280', '900300',
       '900310', '900340', '950110', '950180'], dtype=object)

In [21]:
import MySQLdb

db = MySQLdb.connect(host = 'localhost', port = 3306, user = 'root', passwd = '1234')
cursor = db.cursor()

In [22]:
sql = 'show databases;'
pd.read_sql(sql, db)

             Database
0  information_schema
1           employees
2               mysql
3  performance_schema
4              sakila
5              shopdb
6               sqldb
7                 sys
8             tabledb
9               world

In [25]:
sql = 'use finance_db'
cursor.execute(sql)

0

In [34]:
sql = """
create table if not exists stock_table(
code char(6),
date date,
close float,
margin float,
start float,
high float,
low float,
volume float
)
"""

cursor.execute(sql)

0

In [27]:
url = 'https://finance.naver.com/item/sise_day.naver?code{}&page={}'.format(code, num)

NameError: name 'code' is not defined

In [35]:
url = 'https://finance.naver.com/item/sise_day.naver?code={}&page={}'


for code in codes[:3]:
    print(code, '=========')
    
    for i in range(1, 10):
        driver.get(url.format(code, i))
        time.sleep(0.5)
        html = driver.page_source
        
        df = pd.read_html(html)[0]
        df.dropna(inplace = True)
        print(df)
        print('----------')
        
        for i in range(len(df)):
            code = code
            date = df.iloc[i][0]
            close = df.iloc[i][1]
            margin = df.iloc[i][2]
            start = df.iloc[i][3]
            high = df.iloc[i][4]
            low = df.iloc[i][5]
            volume = df.iloc[i][6]
            
            sql = """
            insert into stock_table values('{}', '{}', '{}', '{}', '{}', '{}', '{}', '{}');
            """.format(code, date, close, margin, start, high, low, volume)

000210 =========
            날짜       종가     전일비       시가       고가       저가       거래량
1   2022.02.09  60300.0   700.0  59700.0  60400.0  59000.0   12179.0
2   2022.02.08  59600.0  1000.0  59100.0  61000.0  58600.0   83130.0
3   2022.02.07  58600.0  1100.0  57500.0  58800.0  57000.0   53386.0
4   2022.02.04  57500.0   900.0  56900.0  57800.0  56600.0   34228.0
5   2022.02.03  56600.0   700.0  56300.0  57500.0  56300.0   44961.0
9   2022.01.28  55900.0  1700.0  54400.0  57500.0  53900.0   95644.0
10  2022.01.27  54200.0  2800.0  57000.0  57100.0  53900.0   97345.0
11  2022.01.26  57000.0   100.0  56600.0  57800.0  56600.0   39639.0
12  2022.01.25  57100.0  1600.0  58200.0  58500.0  56600.0  106342.0
13  2022.01.24  58700.0  1700.0  59300.0  61000.0  58300.0  120883.0
----------
            날짜       종가     전일비       시가       고가       저가       거래량
1   2022.01.21  60400.0  2500.0  61500.0  63100.0  59900.0  138791.0
2   2022.01.20  62900.0   100.0  62700.0  64100.0  62700.0   34951.0
3   2022.01.19  63000.0   600.0  62700.0  64800.0  62100.0   72613.0
4   2022.01.18  62400.0  2200.0  64200.0  64800.0  62300.0   45714.0
5   2022.01.17  64600.0   100.0  63800.0  65000.0  63700.0   56524.0
9   2022.01.14  64500.0  1100.0  65500.0  65500.0  64500.0   57603.0
10  2022.01.13  65600.0  1300.0  66700.0  67200.0  65600.0   52654.0
11  2022.01.12  66900.0  1100.0  65300.0  67100.0  65300.0   84094.0
12  2022.01.11  65800.0   300.0  65200.0  66400.0  64900.0   77633.0
13  2022.01.10  66100.0   100.0  66100.0  67200.0  65700.0   68614.0
----------
            날짜       종가     전일비       시가       고가       저가       거래량
1   2022.01.07  66200.0  1300.0  64100.0  66600.0  63700.0  131944.0
2   2022.01.06  64900.0   300.0  64300.0  65100.0  63900.0   97751.0
3   2022.01.05  64600.0   800.0  63300.0  65700.0  63100.0  145967.0
4   2022.01.04  63800.0  2400.0  61100.0  63800.0  60900.0   83961.0
5   2022.01.03  61400.0   500.0  61000.0  61700.0  60900.0   43780.0
9   2021.12.30  60900.0   700.0  61500.0  61600.0  60400.0   74554.0
10  2021.12.29  61600.0  1400.0  62300.0  62700.0  61600.0   74762.0
11  2021.12.28  63000.0     0.0  63500.0  63500.0  62200.0   77249.0
12  2021.12.27  63000.0   900.0  63900.0  64400.0  62600.0   54725.0
13  2021.12.24  63900.0   200.0  63700.0  64400.0  63500.0   36855.0
----------
            날짜       종가     전일비       시가       고가       저가       거래량
1   2021.12.23  63700.0   200.0  63300.0  63700.0  63000.0   25141.0
2   2021.12.22  63500.0   700.0  62900.0  63900.0  62800.0   37836.0
3   2021.12.21  62800.0   500.0  63800.0  63900.0  62200.0   46287.0
4   2021.12.20  63300.0  1200.0  64100.0  64700.0  63300.0   59286.0
5   2021.12.17  64500.0  2300.0  61200.0  64500.0  61200.0  109884.0
9   2021.12.16  62200.0   100.0  62500.0  63000.0  61500.0   48762.0
10  2021.12.15  62100.0   400.0  62000.0  63300.0  61800.0   32346.0
11  2021.12.14  62500.0   600.0  62600.0  63700.0  62100.0   48895.0
12  2021.12.13  63100.0   400.0  63600.0  63900.0  63000.0   33993.0
13  2021.12.10  63500.0   200.0  63100.0  63700.0  62300.0   46830.0
----------
            날짜       종가     전일비       시가       고가       저가       거래량
1   2021.12.09  63300.0  1000.0  62800.0  63400.0  62400.0   61770.0
2   2021.12.08  62300.0  1100.0  63900.0  64300.0  62000.0   74698.0
3   2021.12.07  63400.0   300.0  63000.0  63600.0  62600.0   46090.0
4   2021.12.06  63100.0  1300.0  61800.0  63800.0  60900.0   85650.0
5   2021.12.03  61800.0   500.0  60400.0  62300.0  60400.0   93279.0
9   2021.12.02  61300.0  2300.0  58200.0  61500.0  57500.0   94943.0
10  2021.12.01  59000.0  3000.0  56000.0  59800.0  55700.0  148059.0
11  2021.11.30  56000.0  2300.0  58900.0  59900.0  55400.0  182753.0
12  2021.11.29  58300.0  1100.0  58100.0  59400.0  57900.0  114228.0
13  2021.11.26  59400.0   900.0  60200.0  60400.0  58900.0  104391.0
----------
            날짜       종가     전일비       시가       고가       저가       거래량
1   2021.11.25  60300.0   800.0  61100.0  61200.0  60000.0   96672.0
2   2021.11.24  61100.0   300.0  61100.0  62000.0  60700.0   60067.0
3   2021.11.23  61400.0   200.0  61000.0  61900.0  60700.0   85924.0
4   2021.11.22  61600.0   200.0  60700.0  61800.0  60400.0  126053.0
5   2021.11.19  61400.0   100.0  61700.0  62100.0  60800.0   59791.0
9   2021.11.18  61500.0   600.0  61000.0  62100.0  60400.0  116640.0
10  2021.11.17  60900.0  2900.0  63800.0  64300.0  60500.0  275803.0
11  2021.11.16  63800.0  1000.0  64400.0  65200.0  63700.0   86043.0
12  2021.11.15  64800.0   500.0  65000.0  65100.0  64200.0   42811.0
13  2021.11.12  64300.0   700.0  63600.0  64700.0  63600.0   46445.0
----------
            날짜       종가     전일비       시가       고가       저가       거래량
1   2021.11.11  63600.0   600.0  63600.0  64400.0  63100.0   70022.0
2   2021.11.10  64200.0  1100.0  64300.0  64900.0  63700.0   80956.0
3   2021.11.09  65300.0   200.0  64800.0  66400.0  64700.0   56973.0
4   2021.11.08  65100.0  1200.0  63900.0  65300.0  63100.0   91969.0
5   2021.11.05  63900.0  1400.0  65700.0  65800.0  63400.0  198892.0
9   2021.11.04  65300.0  1100.0  66700.0  67200.0  64900.0  126260.0
10  2021.11.03  66400.0  1600.0  68000.0  68200.0  66100.0   76691.0
11  2021.11.02  68000.0   800.0  67300.0  68400.0  67300.0   57845.0
12  2021.11.01  67200.0  1500.0  66500.0  67700.0  66400.0   73362.0
13  2021.10.29  65700.0  1000.0  66800.0  67400.0  65500.0   92449.0
----------
            날짜       종가     전일비       시가       고가       저가       거래량
1   2021.10.28  66700.0  1400.0  67900.0  68200.0  66300.0  130293.0
2   2021.10.27  68100.0   600.0  69000.0  69000.0  67300.0   77766.0
3   2021.10.26  68700.0   600.0  68200.0  68700.0  67800.0   46342.0
4   2021.10.25  68100.0   100.0  67600.0  68200.0  67400.0   39274.0
5   2021.10.22  68000.0   100.0  67700.0  68600.0  67600.0   59090.0
9   2021.10.21  68100.0   100.0  68400.0  68400.0  67000.0   83671.0
10  2021.10.20  68200.0   900.0  69500.0  69500.0  67800.0  122935.0
11  2021.10.19  69100.0   100.0  69400.0  69500.0  68800.0   45737.0
12  2021.10.18  69000.0   700.0  69800.0  69900.0  68500.0   67592.0
13  2021.10.15  69700.0   500.0  69600.0  70100.0  69100.0   70293.0
----------
            날짜       종가     전일비       시가       고가       저가       거래량
1   2021.10.14  69200.0   100.0  69300.0  69700.0  68900.0   66858.0
2   2021.10.13  69100.0   200.0  69300.0  69900.0  68700.0   80713.0
3   2021.10.12  69300.0   600.0  69500.0  70300.0  68900.0   79473.0
4   2021.10.08  69900.0   700.0  70800.0  71200.0  69600.0   92007.0
5   2021.10.07  70600.0  1600.0  69300.0  70700.0  69300.0  122751.0
9   2021.10.06  69000.0  2600.0  72100.0  72200.0  68900.0  221165.0
10  2021.10.05  71600.0  2400.0  73500.0  73600.0  70900.0  173821.0
11  2021.10.01  74000.0  1900.0  74700.0  76900.0  74000.0  117980.0
12  2021.09.30  75900.0  2300.0  73800.0  76700.0  73700.0  187817.0
13  2021.09.29  73600.0  2700.0  76100.0  77400.0  72800.0  338312.0
----------
000220 =========
            날짜      종가     전일비      시가      고가      저가        거래량
1   2022.02.09  8730.0  1550.0  7220.0  8880.0  7200.0  8917514.0
2   2022.02.08  7180.0   100.0  7250.0  7310.0  7110.0   103370.0
3   2022.02.07  7280.0    80.0  7250.0  7340.0  7110.0   141024.0
4   2022.02.04  7200.0    20.0  7120.0  7290.0  7080.0   160387.0
5   2022.02.03  7180.0   360.0  6970.0  7600.0  6930.0   566487.0
9   2022.01.28  6820.0   400.0  6420.0  6900.0  6420.0   374772.0
10  2022.01.27  6420.0   280.0  6750.0  6770.0  6410.0   184288.0
11  2022.01.26  6700.0    70.0  6580.0  6930.0  6580.0   199668.0
12  2022.01.25  6630.0   360.0  7060.0  7090.0  6610.0   302898.0
13  2022.01.24  6990.0   220.0  7230.0  7330.0  6990.0   126579.0
----------
            날짜      종가    전일비      시가      고가      저가        거래량
1   2022.01.21  7210.0   10.0  7160.0  7420.0  7130.0   131155.0
2   2022.01.20  7200.0   40.0  7120.0  7260.0  7120.0   112661.0
3   2022.01.19  7160.0  140.0  7270.0  7380.0  7130.0   111781.0
4   2022.01.18  7300.0  200.0  7580.0  7720.0  7270.0   244286.0
5   2022.01.17  7500.0   70.0  7690.0  8090.0  7450.0   691511.0
9   2022.01.14  7570.0   60.0  7510.0  8300.0  7430.0  2150515.0
10  2022.01.13  7510.0  150.0  7450.0  7580.0  7390.0   197071.0
11  2022.01.12  7360.0  180.0  7190.0  7460.0  7190.0   170144.0
12  2022.01.11  7180.0  270.0  7490.0  7530.0  7150.0   214714.0
13  2022.01.10  7450.0   70.0  7530.0  7580.0  7450.0   136629.0
----------

            날짜      종가    전일비      시가      고가      저가       거래량
1   2022.01.07  7520.0    0.0  7510.0  7640.0  7500.0  155155.0
2   2022.01.06  7520.0   70.0  7420.0  8120.0  7410.0  861151.0
3   2022.01.05  7590.0  180.0  7800.0  7860.0  7560.0  221349.0
4   2022.01.04  7770.0   50.0  7860.0  7870.0  7710.0  146023.0
5   2022.01.03  7820.0   10.0  7820.0  7850.0  7700.0  145435.0
9   2021.12.30  7810.0   20.0  7890.0  7980.0  7800.0  228236.0
10  2021.12.29  7830.0   50.0  7750.0  7910.0  7700.0  224211.0
11  2021.12.28  7780.0   40.0  7820.0  7990.0  7740.0  271530.0
12  2021.12.27  7820.0  160.0  7640.0  8200.0  7610.0  647291.0
13  2021.12.24  7660.0  240.0  7950.0  8010.0  7630.0  599306.0
----------
            날짜      종가    전일비      시가      고가      저가        거래량
1   2021.12.23  7900.0  250.0  8050.0  8400.0  7900.0   651825.0
2   2021.12.22  8150.0  120.0  8060.0  8320.0  7970.0   564629.0
3   2021.12.21  8030.0  630.0  8520.0  8520.0  8020.0   841814.0
4   2021.12.20  8660.0  480.0  9000.0  9190.0  8600.0  1111739.0
5   2021.12.17  9140.0  320.0  8890.0  9400.0  8760.0  5565161.0
9   2021.12.16  8820.0  420.0  8680.0  8870.0  8410.0  2487083.0
10  2021.12.15  8400.0  460.0  7940.0  9140.0  7940.0  9156334.0
11  2021.12.14  7940.0  310.0  8250.0  8350.0  7780.0   644906.0
12  2021.12.13  8250.0    0.0  8370.0  8400.0  8180.0   442616.0
13  2021.12.10  8250.0   10.0  8360.0  8700.0  8220.0  1327802.0
----------
            날짜      종가     전일비      시가      고가      저가         거래량
1   2021.12.09  8240.0    60.0  8340.0  8720.0  8230.0   1832468.0
2   2021.12.08  8300.0    80.0  8130.0  9200.0  8010.0   8068264.0
3   2021.12.07  8220.0   600.0  7970.0  9370.0  7960.0  14889066.0
4   2021.12.06  7620.0   390.0  7880.0  7920.0  7510.0   1704662.0
5   2021.12.03  8010.0  1250.0  6830.0  8670.0  6670.0  10453512.0
9   2021.12.02  6760.0   360.0  6330.0  6770.0  6320.0     92308.0
10  2021.12.01  6400.0   100.0  6220.0  6490.0  6220.0    109084.0
11  2021.11.30  6300.0   380.0  6660.0  6760.0  6300.0    194326.0
12  2021.11.29  6680.0   130.0  6810.0  7200.0  6620.0    240746.0
13  2021.11.26  6810.0   110.0  6920.0  6990.0  6750.0     82049.0
----------
            날짜      종가    전일비      시가      고가      저가       거래량
1   2021.11.25  6920.0   50.0  7070.0  7080.0  6920.0   63620.0
2   2021.11.24  6970.0   50.0  6920.0  7090.0  6920.0   92528.0
3   2021.11.23  6920.0   80.0  6850.0  6930.0  6840.0   43604.0
4   2021.11.22  6840.0   50.0  6900.0  6900.0  6810.0   59691.0
5   2021.11.19  6890.0   60.0  6830.0  6890.0  6770.0  111468.0
9   2021.11.18  6830.0  120.0  6880.0  6960.0  6830.0   93025.0
10  2021.11.17  6950.0   80.0  7030.0  7070.0  6900.0   86996.0
11  2021.11.16  7030.0  120.0  7190.0  7190.0  7000.0   57851.0
12  2021.11.15  7150.0  140.0  7130.0  7210.0  7020.0   69318.0
13  2021.11.12  7010.0  120.0  6930.0  7050.0  6920.0   51135.0
----------
            날짜      종가    전일비      시가      고가      저가       거래량
1   2021.11.11  6890.0   40.0  6850.0  7080.0  6850.0   50478.0
2   2021.11.10  6930.0  130.0  7060.0  7080.0  6930.0   84145.0
3   2021.11.09  7060.0   50.0  7080.0  7160.0  7040.0   67253.0
4   2021.11.08  7110.0  190.0  7250.0  7270.0  7050.0  117518.0
5   2021.11.05  7300.0   20.0  7360.0  7390.0  7230.0   60591.0
9   2021.11.04  7320.0   70.0  7390.0  7570.0  7300.0   71821.0
10  2021.11.03  7390.0  110.0  7510.0  7590.0  7380.0   49958.0
11  2021.11.02  7500.0  180.0  7260.0  7580.0  7260.0  102875.0
12  2021.11.01  7320.0  100.0  7420.0  7430.0  7300.0   50979.0
13  2021.10.29  7420.0  130.0  7550.0  7590.0  7330.0   70607.0
----------
            날짜      종가   전일비      시가      고가      저가       거래량
1   2021.10.28  7550.0  90.0  7600.0  7680.0  7540.0   57217.0
2   2021.10.27  7640.0  40.0  7690.0  7720.0  7640.0   53240.0
3   2021.10.26  7680.0  40.0  7570.0  7700.0  7570.0   81724.0
4   2021.10.25  7640.0  30.0  7670.0  8040.0  7570.0   91847.0
5   2021.10.22  7670.0  50.0  7640.0  7880.0  7560.0  118149.0
9   2021.10.21  7620.0  40.0  7660.0  7710.0  7570.0   54693.0
10  2021.10.20  7660.0  60.0  7650.0  7720.0  7580.0   95678.0
11  2021.10.19  7600.0  40.0  7500.0  7660.0  7500.0   44369.0
12  2021.10.18  7560.0  80.0  7700.0  7700.0  7470.0   43430.0
13  2021.10.15  7640.0  10.0  7800.0  7800.0  7540.0  101372.0
----------
            날짜      종가    전일비      시가      고가      저가       거래량
1   2021.10.14  7650.0  130.0  7520.0  7760.0  7520.0   71968.0
2   2021.10.13  7520.0  160.0  7370.0  7750.0  7370.0  117620.0
3   2021.10.12  7360.0  130.0  7200.0  7400.0  7100.0   87112.0
4   2021.10.08  7230.0   10.0  7220.0  7350.0  7150.0   62619.0
5   2021.10.07  7220.0  290.0  6930.0  7250.0  6920.0  132321.0
9   2021.10.06  6930.0  330.0  7240.0  7420.0  6850.0  254913.0
10  2021.10.05  7260.0  480.0  7610.0  7660.0  7200.0  208727.0
11  2021.10.01  7740.0  350.0  8010.0  8060.0  7720.0  154530.0
12  2021.09.30  8090.0  130.0  7930.0  8150.0  7930.0   79161.0
13  2021.09.29  7960.0  100.0  7820.0  8020.0  7810.0  106102.0
----------
000240 =========
            날짜       종가    전일비       시가       고가       저가       거래량
1   2022.02.09  13650.0  200.0  13650.0  13700.0  13500.0   16654.0
2   2022.02.08  13450.0  250.0  13700.0  14000.0  13400.0   87066.0
3   2022.02.07  13700.0  200.0  13500.0  13800.0  13200.0   87461.0
4   2022.02.04  13500.0  100.0  13300.0  13600.0  13250.0   56484.0
5   2022.02.03  13400.0  450.0  13200.0  13800.0  13100.0  104055.0
9   2022.01.28  12950.0  600.0  12350.0  13100.0  12200.0  121177.0
10  2022.01.27  12350.0  700.0  12950.0  13050.0  12350.0  200947.0
11  2022.01.26  13050.0    0.0  13250.0  13350.0  12750.0  101128.0
12  2022.01.25  13050.0  500.0  13600.0  13650.0  12900.0  216723.0
13  2022.01.24  13550.0  300.0  13750.0  14000.0  13450.0  125162.0
----------
            날짜       종가    전일비       시가       고가       저가       거래량
1   2022.01.21  13850.0  200.0  13900.0  14150.0  13850.0   45679.0
2   2022.01.20  14050.0   50.0  13900.0  14100.0  13800.0   77912.0
3   2022.01.19  14100.0   50.0  13950.0  14150.0  13750.0  106121.0
4   2022.01.18  14050.0  400.0  14550.0  14650.0  14000.0   84551.0
5   2022.01.17  14450.0  200.0  14600.0  14600.0  14300.0   71959.0
9   2022.01.14  14650.0  250.0  14800.0  14800.0  14550.0   98298.0
10  2022.01.13  14900.0  100.0  15000.0  15150.0  14800.0   58713.0
11  2022.01.12  15000.0  300.0  14750.0  15150.0  14700.0   99063.0
12  2022.01.11  14700.0  350.0  14950.0  15100.0  14700.0  116065.0
13  2022.01.10  15050.0  200.0  15200.0  15350.0  14950.0   64877.0
----------
            날짜       종가    전일비       시가       고가       저가       거래량
1   2022.01.07  15250.0   50.0  15300.0  15450.0  15100.0   74503.0
2   2022.01.06  15200.0  350.0  15450.0  15500.0  15150.0  114026.0
3   2022.01.05  15550.0  150.0  15850.0  15850.0  15500.0   77898.0
4   2022.01.04  15700.0  150.0  15550.0  15750.0  15400.0   87125.0
5   2022.01.03  15550.0  150.0  15800.0  15800.0  15500.0   78770.0
9   2021.12.30  15700.0  200.0  15850.0  15900.0  15550.0   90782.0
10  2021.12.29  15900.0  350.0  16150.0  16250.0  15900.0  120000.0
11  2021.12.28  16250.0  250.0  16000.0  16350.0  15950.0  230749.0
12  2021.12.27  16000.0  150.0  16250.0  16250.0  15950.0   57328.0
13  2021.12.24  16150.0  250.0  15950.0  16200.0  15950.0  101837.0
----------
            날짜       종가    전일비       시가       고가       저가       거래량
1   2021.12.23  15900.0  150.0  15700.0  15950.0  15700.0   56385.0
2   2021.12.22  15750.0  200.0  15500.0  15800.0  15450.0  107122.0
3   2021.12.21  15550.0   50.0  15550.0  15650.0  15400.0  101186.0
4   2021.12.20  15600.0   50.0  15600.0  16000.0  15500.0   98094.0
5   2021.12.17  15550.0  100.0  15650.0  15800.0  15500.0   70076.0
9   2021.12.16  15650.0   50.0  15800.0  16000.0  15450.0   86388.0
10  2021.12.15  15700.0  200.0  15900.0  15950.0  15700.0   59322.0
11  2021.12.14  15900.0  100.0  15950.0  16150.0  15700.0   81006.0
12  2021.12.13  16000.0  150.0  16250.0  16400.0  15950.0  133640.0
13  2021.12.10  16150.0  300.0  16250.0  16400.0  16000.0   89880.0
----------
            날짜       종가    전일비       시가       고가       저가       거래량
1   2021.12.09  16450.0  250.0  16300.0  16450.0  16100.0  113338.0
2   2021.12.08  16200.0    0.0  16250.0  16600.0  16100.0  101893.0
3   2021.12.07  16200.0  100.0  16250.0  16350.0  16050.0   66979.0
4   2021.12.06  16100.0  300.0  16200.0  16400.0  16000.0   74510.0
5   2021.12.03  16400.0  250.0  16250.0  16500.0  16000.0  115777.0
9   2021.12.02  16150.0  650.0  15450.0  16400.0  15200.0  178282.0
10  2021.12.01  15500.0  350.0  15200.0  15700.0  15100.0  147985.0
11  2021.11.30  15150.0   50.0  15500.0  16000.0  15050.0  200566.0
12  2021.11.29  15200.0  300.0  15350.0  15600.0  15050.0   97556.0
13  2021.11.26  15500.0  200.0  15750.0  15800.0  15500.0   84232.0
----------

            날짜       종가    전일비       시가       고가       저가       거래량
1   2021.11.25  15700.0  300.0  16000.0  16000.0  15500.0  121274.0
2   2021.11.24  16000.0   50.0  16100.0  16450.0  15800.0   93702.0
3   2021.11.23  16050.0  400.0  16250.0  16300.0  16000.0  103957.0
4   2021.11.22  16450.0  250.0  16200.0  16500.0  16100.0   66504.0
5   2021.11.19  16200.0  100.0  16300.0  16500.0  16150.0   68227.0
9   2021.11.18  16300.0  200.0  16550.0  16550.0  16250.0   74168.0
10  2021.11.17  16500.0  600.0  17000.0  17000.0  16450.0  140337.0
11  2021.11.16  17100.0  250.0  17250.0  17350.0  16950.0   94762.0
12  2021.11.15  17350.0  250.0  16950.0  17400.0  16950.0   75794.0
13  2021.11.12  17100.0  250.0  16800.0  17150.0  16800.0   53068.0
----------
            날짜       종가    전일비       시가       고가       저가       거래량
1   2021.11.11  16850.0  200.0  16950.0  17250.0  16650.0  107040.0
2   2021.11.10  17050.0  400.0  17300.0  17500.0  16950.0   78411.0
3   2021.11.09  17450.0  150.0  17700.0  17800.0  17200.0  137949.0
4   2021.11.08  17600.0  300.0  17300.0  17900.0  17050.0  207873.0
5   2021.11.05  17300.0  450.0  17750.0  17800.0  17050.0  223713.0
9   2021.11.04  17750.0  650.0  17200.0  18000.0  17200.0  318794.0
10  2021.11.03  17100.0  250.0  17250.0  17450.0  17050.0   72590.0
11  2021.11.02  17350.0  750.0  16650.0  17400.0  16650.0  130055.0
12  2021.11.01  16600.0  100.0  16600.0  16900.0  16450.0  116537.0
13  2021.10.29  16700.0   50.0  16700.0  16850.0  16400.0   58492.0
----------
            날짜       종가    전일비       시가       고가       저가       거래량
1   2021.10.28  16650.0  650.0  17150.0  17300.0  16650.0   88672.0
2   2021.10.27  17300.0   50.0  17350.0  17350.0  17050.0   48393.0
3   2021.10.26  17350.0  100.0  17250.0  17400.0  17150.0   46456.0
4   2021.10.25  17250.0  100.0  17200.0  17350.0  17050.0   57107.0
5   2021.10.22  17350.0  150.0  17450.0  17550.0  17200.0   67186.0
9   2021.10.21  17500.0  150.0  17250.0  17550.0  17100.0   96170.0
10  2021.10.20  17350.0  400.0  17600.0  17750.0  17150.0  117273.0
11  2021.10.19  17750.0  100.0  17800.0  17950.0  17600.0  109859.0
12  2021.10.18  17650.0  150.0  17850.0  17850.0  17550.0  107945.0
13  2021.10.15  17800.0  300.0  17550.0  17950.0  17500.0  225444.0
----------
            날짜       종가    전일비       시가       고가       저가       거래량
1   2021.10.14  17500.0  300.0  17250.0  17550.0  16950.0  129707.0
2   2021.10.13  17200.0  100.0  17000.0  17350.0  16950.0  110138.0
3   2021.10.12  17100.0  600.0  16600.0  17350.0  16550.0  312010.0
4   2021.10.08  16500.0  500.0  16000.0  16550.0  15800.0  176041.0
5   2021.10.07  16000.0  250.0  15800.0  16150.0  15750.0  117443.0
9   2021.10.06  15750.0  150.0  15850.0  16050.0  15350.0  118322.0
10  2021.10.05  15600.0    0.0  15450.0  15900.0  15000.0  234693.0
11  2021.10.01  15600.0  300.0  15650.0  15850.0  15450.0  177979.0
12  2021.09.30  15900.0  150.0  15600.0  16050.0  15600.0  133198.0
13  2021.09.29  15750.0  350.0  15900.0  16050.0  15550.0  192032.0
----------

In [36]:
sql = 'select * from stock_table;'

pd.read_sql(sql, db)

Empty DataFrame
Columns: [code, date, close, margin, start, high, low, volume]
Index: []